- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

- name: convert to uppercase
  vars:
    greetings: "Hello Ramesh"
  ansible.builtin.debug:
    msg: "{{ greetings | upper}}"

- name: convert to lowercase
  vars:
    greetings: "Hello Ramesh"
  ansible.builtin.debug:
    msg: "{{ greetings | upper}}"    